### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by nmrugg** [manuels/unix-toolbox.js-imagemagick#1]
Any chance you can explain how to compile the JavaScript yourself? I'm try to add webp support, and I can't figure out how you used emscripten to build it. I just keep getting the error:
<code>ERROR    root: 1: No such file or directory</code>

Thanks.

**Comment by manuels** [comment]
You will need to download emscripten and put it into your PATH

Am 11.12.2013 15:58, schrieb Nathan Rugg:

**Comment by nmrugg** [comment]
Yeah, I did that.

I was actually able to fix the issue by deleting "-minify 1" from the Makefile. I'm not sure why, but that made the "No such file or directory" error disappear.

I'll let you know if I come across any other problems.

**Comment by hhm0** [comment]
The issue is that the `minify` argument requires two dashes (`--`) before it.

This happened to me just now, only with `-closure` :-)

Using `strace -e file <cmd>` helped locate the culprit: emscripten is looking for files called `-closure` and `1`, since it thinks these are files to compile. It seems that basically anything which does not start with `--` is considered a compiler input :-).

**Comment by manuels** [comment]
Great, thanks @hhm0!
